### ISSUE TITLE
Show current line number incorrect with code folding

### ISSUE THREAD

**Issue by quicknir** [matf/relativenumberruler#5]
There seems to be a bug that shows up when something is folded. Basically, folded code does not count towards the current line number. It's a bit of an awkward situation because it's probably desirable not to count folded code when talking about relative line number (for the purpose of moving around quickly with vim), but when you activate showing the current line number in place of 0, it shows the wrong line which is undesirable.

**Comment by matf** [comment]
This is actually by design. This plugin was designed to be used with Vrapper (vim-like plugin for Eclipse). Vrapper treats folded lines the same way as the ruler, i.e. jumping down 5 lines by pressing '5j' will move down 5 displayed lines, and not 5 real lines, ignoring any folded lines.

I can add a preference switch to toggle this behaviour.

**Comment by quicknir** [comment]
Is it possible to leave it so that the relative line numbering stay the same, but the absolute line number (only the number on the same line as the cursor) is correct?

**Comment by quicknir** [comment]
Let me explain using a picture. If you look at the attached image, it's Eclipse with a simple chunk of open code, including a folded comment. I have both your relative line number plugin, and regular line numbering open. I also have the "Show Absolute Line Number" on current line ticked off.

The fact that RNL labels the '#include <vector>' line with a 5 should not change. I'm a vrapper user myself and this is the correct number if I wanted to use 5k to jump up to that line.

The issue is that the absolute line number at the cursor is not correct, it shows 6 instead of 11. I use Vrapper regularly and I've never made use of this value of 6 (i.e. the number of lines counting down from the top to your current position, skipping folds). It doesn't really serve much purpose. I suppose if you went to the top of the file you could use 6j to return to where you were, but you could also just use :11.

The reason this is annoying is because compiler errors and warnings, failed unit tests, etc, tend to all state the line number. When investigating these, it's helpful to have the correct absolute line number easily available (instead of having to look at the bottom right, which you'll notice shows the right value). Is it possible to change, or offer a preference, to change only the behavior of the absolute line number under the cursor? 

I'll also mention that this is inconsistent with vim's behavior, see the two attached screenshots. In other words, if Vim were folding the same text as Eclipse and using the hybrid line numbering mode, it would show 11 not 6 on the line with the cursor.

![screenshot from 2015-10-06 09 16 02](https://cloud.githubusercontent.com/assets/10457096/10309519/08e24846-6c0b-11e5-8361-405eae5102cb.png)
![screenshot from 2015-10-06 09 27 03](https://cloud.githubusercontent.com/assets/10457096/10309866/e35adf14-6c0c-11e5-8d22-0399cc3e744c.png)
![screenshot from 2015-10-06 09 28 26](https://cloud.githubusercontent.com/assets/10457096/10309868/e58381ec-6c0c-11e5-9589-4b294a0e2c98.png)

**Comment by matf** [comment]
I read your initial issue text in a hurry and missed the details. You're right, the absolute number display should correspond to the actual line in the file and not care about folded text. Will reopen your PR.

**Comment by matf** [comment]
Published 1.2.0, please update from the update site. Verified to work in Luna and Mars.

Thanks a lot for taking the time to create the PR.

**Comment by quicknir** [comment]
@matf @selevt Just wanted to thank both of you for putting in the time to fix this, and more generally Matt for maintaining this awesome plugin. Thanks!
