### ISSUE TITLE
Eclipse Marketplace

### ISSUE THREAD

**Issue by sirolf2009** [matf/relativenumberruler#8]
Could you add this plugin to the market place? I want to favorite it so it can be downloaded automatically when I'm updating to a new eclipse

**Comment by matf** [comment]
I have made an attempt to add it to the marketplace at https://marketplace.eclipse.org/content/relative-line-number-ruler

It is currently awaiting moderation. Please let me know via this issue whether it works for you or not as soon as it has been published.

**Comment by sirolf2009** [comment]
it works!

**Comment by matf** [comment]
Good to know, thanks for reporting
